version: "3.9"
services:
  backend:
    image: "xyzassessment/backend-services"
    ports:
      - "8080"

  aggregator:
    image: "fedex/api-service-aggregator"
    container_name: aggregator
    ports:
      - "8181:8181"
    environment:
      BACKEND_HOST: backend
      BACKEND_PORT: 8080
      SERVER_HOST: 0.0.0.0
      SERVER_PORT: 8181
      LOG_LEVEL: INFO
    depends_on:
      - backend